### ISSUE TITLE
banned IP are not blocked

### ISSUE THREAD

**Issue by erdoukki** [peci1/fail2ban_openwrt#2]
https://forum.openwrt.org/t/fail2ban-and-iptables-ip-bans-not-blocked/90057

**Comment by erdoukki** [comment]
resolved by adding in jail.local the following : 
```
[DEFAULT]
chain = FORWARD
```

**Comment by peci1** [comment]
Thanks. Although it's not really an issue of this project, I added a paragraph to the README that guides the users to configuring the jail like you did in case they need to block traffic to LAN devices or containers.

https://github.com/peci1/fail2ban_openwrt/commit/3471a418c09028388d1ca4fbebc10a206a1dea81
