### ISSUE TITLE
ipk packaging request

### ISSUE THREAD

**Issue by erdoukki** [peci1/fail2ban_openwrt#4]
Will you plan to forge an ipk package for OpenWrt and to upstream it ?

**Comment by peci1** [comment]
Hi @erdoukki , thanks for all your improvements. I'm a but busy now but I promise to not forget about them and to get back to each of them.

I have no experience with openwrt packaging. If you could be of any help here, it would be greatly appreciated.

**Comment by erdoukki** [comment]
already done a package some years ago, will try to go in it again for fail2ban...
ref : https://openwrt.org/docs/guide-developer/packages

**Comment by erdoukki** [comment]
https://github.com/sartura/openwrt-packages/tree/master/lang/python

**Comment by erdoukki** [comment]
https://forum.openwrt.org/t/fail2ban-packaging-for-openwrt-and-python3/90764

initial version package built with success !
https://github.com/erdoukki/fail2ban_openwrt/commit/a38183aafd9c86817aa35d3b49034c1c3b49f5d0#diff-bc4a71180870f7945155fbb02f4b0a2e3faa2a62d6d31b7039013055ed19869a

necessary files are here : https://github.com/erdoukki/fail2ban_openwrt/tree/master/package

https://github.com/erdoukki/vrac/blob/master/fail2ban_0.11.2-1_aarch64_cortex-a53.ipk
https://github.com/erdoukki/vrac/blob/master/python3-pyinotify_0.9.6-1_aarch64_cortex-a53.ipk

**Comment by erdoukki** [comment]
still need somes fixes...

here first issues and tests : 
```
root@BORNE3:~# ls -hal /usr/bin/fail2ban-python 
lrwxrwxrwx    1 root     root          83 Mar  9 17:11 /usr/bin/fail2ban-python -> /media/gerald/EBINDEV/DEVEL/OWRT/snapshot/openwrt/staging_dir/hostpkg/bin/python3.9

root@BORNE3:~# rm /usr/bin/fail2ban-python
root@BORNE3:~# ln -s /usr/bin/python3 /usr/bin/fail2ban-python
root@BORNE3:~# fail2ban-python --version
Python 3.7.10
root@BORNE3:~# fail2ban-server 
Traceback (most recent call last):
  File "/usr/bin/fail2ban-server", line 34, in <module>
    from fail2ban.client.fail2banserver import exec_command_line, sys
ModuleNotFoundError: No module named 'fail2ban'
root@BORNE3:~# fail2ban-server --version
Traceback (most recent call last):
  File "/usr/bin/fail2ban-server", line 34, in <module>
    from fail2ban.client.fail2banserver import exec_command_line, sys
ModuleNotFoundError: No module named 'fail2ban'
root@BORNE3:~#
 
```

**Comment by erdoukki** [comment]
may appear because I am cross compiling for one python version and testing on another !

**Comment by erdoukki** [comment]
forcing the installation on a 19.07.7 of all python 3.9.2 version necessary packages and overwriting libsqlite and libbz for dependencies and quick testing ;
working well ! 
```
root@BORNE3:~# fail2ban-server --version
Fail2Ban v0.11.2
```
```
root@BORNE3:~# fail2ban-python --version
Python 3.9.2
```

**Comment by erdoukki** [comment]
need now to tweak the first installation (or not) but package is building and is working !

**Comment by erdoukki** [comment]
https://github.com/erdoukki/fail2ban_openwrt/issues/6
Package ok in 19.07.x !

**Comment by erdoukki** [comment]
binaries (in arch all) https://github.com/erdoukki/fail2ban_openwrt/tree/master/binary/custom-19.07

**Comment by erdoukki** [comment]
https://github.com/openwrt/packages/pull/15095

**Comment by erdoukki** [comment]
https://github.com/openwrt/packages/pull/15098 for MR

**Comment by peci1** [comment]
Great! Thanks for taking care. I'll test the binaries and let you know.

**Comment by erdoukki** [comment]
if needed, I just uploaded snapshot binaries fo the day, for arch all ! ;-) 
https://github.com/erdoukki/fail2ban_openwrt/tree/master/binary/master

**Comment by erdoukki** [comment]
looks like not arch all compatible ! sorry...
https://github.com/erdoukki/fail2ban_openwrt/issues/7
