### ISSUE TITLE
Is there a specific tutorial on how to install and use it? For my non-programmer

### ISSUE THREAD

**Issue by wyfang** [peci1/fail2ban_openwrt#7]
I'm sorry if I can't post it here.

**Comment by peci1** [comment]
Hi, try to follow the instructions in readme and let me know where you get stuck.

In newer versions of OpenWRT, there is also package `fail2ban` available via opkg, so you can try that first. It does not contain the PPtP jail support, but it should be compatible with the install scripts from this package.

**Comment by wyfang** [comment]
Thx! I I installed it successfully using 'opkg install fail2ban' as you said; I checked that there are files in /etc/fail2ban/ and I think it installed successfully. 

![image](https://user-images.githubusercontent.com/17900420/199481230-9fd70d28-12d8-4d3a-9e98-70e6b006a286.png)
What files do I need to download from your github next? What directory do I put them in after downloading? Then run . /install_f2b_config.sh and that's it?

**Comment by peci1** [comment]
That depends on what you want to do. Do you want the PPtP jail, or some others?

**Comment by wyfang** [comment]
I don't  understand what "PPtP" is? My **openwrt** is running on **Proxmox VE** and I have successfully implemented Proxmox VE WebUI and SSH fail2ban settings through tutorials. And my **openwrt** is the same, with Website and SSH, so what should I do?

**Comment by peci1** [comment]
Ok, if you don't know what's PPtP, you don't need it =) It is a VPN and this repo is a combination of general fail2ban install instructions (which are no longer needed as the package is already in opkg) and specific instructions on installation of the PPtP jail. So I think you're all set up.

**Comment by wyfang** [comment]
So yours github doesn't protect the web connection and ssh for openwrt?

**Comment by peci1** [comment]
This repository was created in times when there was no official fail2ban package for OpenWRT. At that times, it was the easiest way to get fail2ban up and running on OpenWRT. Now, there already are official opkg packages for fail2ban, so this repo becomes redundant (up to the PPtP VPN jail part which is still not in official OpenWRT packages).

So the recommended approach now is just `opkg install fail2ban` and then following any fail2ban tutorial you find to protect the services you wish.
